<?php

ini_set('memory_limit', '-1');

$finder = PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->name('*.php')
    ->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setRules([
      '@PSR2' => true,
      'align_multiline_comment' => true,
      'array_indentation' => true,
      'array_syntax' => ['syntax' => 'short'],
      'binary_operator_spaces' => [
          'align_double_arrow' => true,
          'align_equals' => true,
      ],
      'blank_line_after_opening_tag' => true,
      'blank_line_before_statement' => true,
      'blank_line_before_return' => true,
      'cast_spaces' => true,
      'class_attributes_separation' => true,
      'combine_consecutive_unsets' => true,
      'compact_nullable_typehint' => true,
      'concat_space' => ['spacing' => 'one'],
      'declare_equal_normalize' => ['space' => 'single'],
      'explicit_indirect_variable' => true,
      'explicit_string_variable' => true,
      'function_declaration' => true,
      'function_typehint_space' => true,
      'general_phpdoc_annotation_remove' => true,
      'include' => true,
      'increment_style' => true,
      'linebreak_after_opening_tag' => true,
      'list_syntax' => ['syntax' => 'short'],
      'logical_operators' => true,
      'lowercase_cast' => true,
      'magic_constant_casing' => true,
      'method_chaining_indentation' => true,
      'modernize_types_casting' => true,
      'multiline_comment_opening_closing' => true,
      'multiline_whitespace_before_semicolons' => true,
      'native_function_casing' => true,
      'native_function_invocation' => true,
      'new_with_braces' => true,
      'no_alias_functions' => true,
      'no_blank_lines_after_class_opening' => true,
      'no_blank_lines_after_phpdoc' => true,
      'no_empty_comment' => true,
      'no_empty_phpdoc' => true,
      'no_empty_statement' => true,
      'no_extra_blank_lines' => [
        'curly_brace_block',
        'extra',
        'parenthesis_brace_block',
        'square_brace_block',
        'throw',
        'use',
      ],
      'no_leading_import_slash' => true,
      'no_leading_namespace_whitespace' => true,
      'no_mixed_echo_print' => true,
      'no_multiline_whitespace_around_double_arrow' => false,
      'no_null_property_initialization' => true,
      'no_php4_constructor' => true,
      'no_short_bool_cast' => true,
      'no_short_echo_tag' => true,
      'no_singleline_whitespace_before_semicolons' => true,
      'no_spaces_after_function_name' => true,
      'no_spaces_around_offset' => true,
      'no_spaces_inside_parenthesis' => true,
      'no_superfluous_elseif' => true,
      'no_trailing_comma_in_list_call' => true,
      'no_trailing_comma_in_singleline_array' => true,
      'no_unneeded_control_parentheses' => true,
      'no_unneeded_curly_braces' => true,
      'no_unneeded_final_method' => true,
      'no_unused_imports' => true,
      'no_useless_else' => true,
      'no_useless_return' => true,
      'no_whitespace_before_comma_in_array' => true,
      'no_whitespace_in_blank_line' => true,
      'normalize_index_brace' => true,
      'not_operator_with_space' => false,
      'object_operator_without_whitespace' => true,
      'ordered_class_elements' => true,
      'ordered_imports' => true,
      'php_unit_fqcn_annotation' => true,
      'phpdoc_align' => true,
      'phpdoc_annotation_without_dot' => true,
      'phpdoc_indent' => true,
      'phpdoc_inline_tag' => true,
      'phpdoc_no_access' => true,
      'phpdoc_no_alias_tag' => true,
      'phpdoc_no_empty_return' => true,
      'phpdoc_no_package' => true,
      'phpdoc_no_useless_inheritdoc' => true,
      'phpdoc_order' => true,
      'phpdoc_return_self_reference' => true,
      'phpdoc_scalar' => true,
      'phpdoc_separation' => true,
      'phpdoc_single_line_var_spacing' => true,
      'phpdoc_summary' => true,
      'phpdoc_to_comment' => true,
      'phpdoc_trim' => true,
      'phpdoc_types' => true,
      'phpdoc_types_order' => true,
      'phpdoc_var_without_name' => true,
      'psr4' => true,
      'semicolon_after_instruction' => true,
      'short_scalar_cast' => true,
      'simplified_null_return' => true,
      'single_blank_line_before_namespace' => true,
      'single_class_element_per_statement' => true,
      'single_line_comment_style' => true,
      'single_quote' => true,
      'standardize_not_equals' => true,
      'strict_comparison' => true,
      'strict_param' => true,
      'ternary_operator_spaces' => true,
      'ternary_to_null_coalescing' => true,
      'trailing_comma_in_multiline_array' => true,
      'trim_array_spaces' => true,
      'unary_operator_spaces' => true,
      'void_return' => false,
    ])
    ->setRiskyAllowed(true)
    ->setFinder($finder)
    ->setUsingCache(true)
    ->setLineEnding("\n");
